name: face_recognition
description: This is the Face Recognition Flutter app which can be running on both Android & iOS platform.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: 0.10.4
  cupertino_icons: ^1.0.2
  google_ml_vision: 0.0.8
  image_picker: ^0.8.6
  image: ^3.0.2
  tflite_flutter: ^0.8.0
  path_provider: ^2.0.2
  bitmap: ^0.1.2
  lottie: ^1.3.0
  dropdown_button2: ^1.4.0
  dio:
  network_info_plus: ^3.0.1
  aws_rekognition_api: ^2.0.0
  aws_s3_upload: ^1.5.0
  flutter_secure_storage: ^7.0.1
  socket_io_client: 
  flutter_svg: 2.0.6
  google_fonts: 4.0.4
  provider:
  animate_do: 3.0.2
  flutter_spinkit: 5.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
